### ISSUE TITLE
Does bamboo use the Marathon event bus or does it integrate with marathon ZK?

### ISSUE THREAD

**Issue by dgrnbrg** [QubitProducts/bamboo#118]
I am wondering this because one is a public API, and the other's private, but I haven't been able to track down in the codebase which does bamboo use.

**Comment by alexanderjardim** [comment]
It listens for Marathon events in http. So it uses the event bus.

**Comment by activars** [comment]
Correct, it requires enable http_callbacks  @alexanderjardim  thanks for answering those questions.

**Comment by dgrnbrg** [comment]
Thank you!
