### ISSUE TITLE
In GUI, I can update a empty ACL and destroy haproxy config

### ISSUE THREAD

**Issue by hyper-carrot** [QubitProducts/bamboo#119]
I will get the following log if I update a empty ACL:

```
[ALERT] 106/065607 (51) : parsing [/etc/haproxy/haproxy.cfg:1035] : error detected while parsing switching rule : no such ACL : '::myapp-websocket-aclrule'.
```

In fact,  there are the following parts in haproxy.cfg:

```
acl ::myapp-websocket-aclrule 
use_backend ::myapp-websocket-cluster if ::myapp-websocket-aclrule
```

I think that it's not robust.

**Comment by activars** [comment]
The UI and API needs improvements.  When haproxy reload, it should validate whether the content is valid before trigger the reload.

**Comment by hyper-carrot** [comment]
I couldn't agree more

**Comment by bluepeppers** [comment]
See #158

**Comment by bluepeppers** [comment]
Template validation is now supported, @hyper-carrot would you like to keep this open for UI ACL validation, or is this good enough for you?

**Comment by hyper-carrot** [comment]
@bluepeppers Thank you for reminding, but my central focus have changed. So, I will keep my attention in my spare time. :-)

**Comment by bluepeppers** [comment]
Cool, closing then :+1:
