### ISSUE TITLE
Only the first service port is supported in Bamboo model

### ISSUE THREAD

**Issue by Kabhal** [QubitProducts/bamboo#120]
If an application specify multiple services ports, Bamboo manage only the first one.

The fork https://github.com/MiLk/bamboo supports this correctly but is not up-to-date.

**Comment by activars** [comment]
Thanks for the heads up. I'm in the progress reviewing it in the next couple of days. :)
Duplicate #96

**Comment by MiLk** [comment]
@Kabhal I've updated my branch in the case you want to use it.
