### ISSUE TITLE
Not updating haproxy because invalid character

### ISSUE THREAD

**Issue by rhoml** [QubitProducts/bamboo#131]
Using the default template i keep running into with the latest version of Bamboo

```
2015/05/16 10:07:47 Environment variable not set: STATSD_ENABLED
2015/05/16 10:07:47 Not updating haproxy because we failed to retrieve template data:
 invalid character '<' looking for beginning of value
```
* Even if I set export STATSD_ENABLED=false bamboo keeps complaining
* Haproxy doesn't get updated because of a parsing error apparently even if using the default template

**Comment by activars** [comment]
Hi, 

STATSD_ENABLED message is a information only.
Did you configure anything in Bamboo itself? I lookup in the default template, and the character should exists unless it's coming from the user input or information populated from Marathon.

**Comment by rhoml** [comment]
Thanks, 

About the character it was a miss configuration on the latest version on my side.

**Comment by activars** [comment]
Thanks for updating this issue. 
It probably should show some status information in API or UI.

Thanks
