### ISSUE TITLE
bamboo not updating haproxy 

### ISSUE THREAD

**Issue by InformatiQ** [QubitProducts/bamboo#142]
according to https://github.com/QubitProducts/bamboo/blob/master/main/bamboo/bamboo.go#L102
the url for the marathon callback would be http://10.5.0.50:8000/api/marathon/event_callback
which is what i set in marathon
bamboo gets notified of changes and i can see it reflected in the API, but the haproxy doesn't cahnge
and no logs to help

**Comment by activars** [comment]
Hi, it might worth check whether marathon http callback is enabled?

**Comment by InformatiQ** [comment]
It is enabled and bamboo api reflects the changes done in marathon but does
not update haproxy

**Comment by rasputnik** [comment]
You probably need to check your reload command is doing what you expect then.

**Comment by apriendeau** [comment]
@activars we are seeing this as well. We also see this when an application crashes or is redeployed, bamboo wont pick up the changes.

**Comment by activars** [comment]
It's likely that marathon "restart" doesn't trigger callback in recent version.

"Redeploy" should always trigger changes.

Bamboo's log and built-in statsd are the best place to troubleshoot issues. 

One good tips is always checking haproxy stats page. It shows whether the application is added to the load balancing pool and shows state of the application. 

Applications are usually developed in different style or using many web frameworks. Sometime they don't provide correct http implementation, haproxy may not like those health check responses. (I've seen issues with some popular Python and Scala web frameworks)

**Comment by apriendeau** [comment]
So the only problem I see that it is just not pulling the information. I am manually clicking the pencil, and update. This occurs with both with redeploy or restart.

**Comment by activars** [comment]
Does the host running Bamboo be able to curl Marathon host? Marathon and bamboo should be able to communicate with each other.

**Comment by InformatiQ** [comment]
yes they can communicate
@activars as i mentioned, when i make a change in marathon for example, a scale up increasing from 3 to 4 instances (no docker)
i can see the change in reflected through the bamboo api, but the haproxy config is not updated
and i see no logs related
I am using latest release of bamboo not master

**Comment by InformatiQ** [comment]
it was able to fix this by deleting all callback urls from marathon and restarting bamboo

**Comment by apriendeau** [comment]
@InformatiQ I dont know if this is a good solution because that doesnt solve the problem in the long run.
