### ISSUE TITLE
Please support event streaming

### ISSUE THREAD

**Issue by bsideup** [QubitProducts/bamboo#149]
https://mesosphere.github.io/marathon/docs/rest-api.html#event-stream

with Marathon 0.9.0 events could be accessed by listening for event stream, which means that it's no longer required to specify bamboo's callback URL in Marathon. 

This would greatly improve installation process of bamboo and also will allow to scale bamboo without re-specifying event_listeners

**Comment by bluepeppers** [comment]
Sounds like a very good feature. Will have to keep the existing backend for compatability, but streaming should improve matters going forwards

**Comment by bsideup** [comment]
@bluepeppers cool, thanks

**Comment by bsideup** [comment]
@bluepeppers this link could be helpful:

http://tiebing.blogspot.com/2014/06/golang-http-client-server-sent-event.html


BTW maybe you need help with implementation?

**Comment by bluepeppers** [comment]
If you want to take a shot at it, PR are always welcome. Will poke at it over the weekend probably. Thanks for the link.

**Comment by bsideup** [comment]
@bluepeppers ok, will try. Any chance of mentorship if I will have questions?:)

**Comment by bluepeppers** [comment]
Sure :) Feel free to send me an email if you have any specific questions: laurie@qubit.com

**Comment by bsideup** [comment]
@bluepeppers here we go: https://github.com/QubitProducts/bamboo/pull/151 :)

**Comment by xiaods** [comment]
+1
