### ISSUE TITLE
Support timeouts on reloads

### ISSUE THREAD

**Issue by gregory90** [QubitProducts/bamboo#150]
I'm running bamboo using docker container.
Bamboo won't start another reload while one is pending, but sometimes(very seldom) it happens that haproxy reload hangs forever.
Logs: https://gist.github.com/gregory90/dae71eccb927d9cc4019

**Comment by bluepeppers** [comment]
Would a timeout on reloads be enough?

**Comment by gregory90** [comment]
It would be perfect:)

**Comment by timoreimann** [comment]
Hanging HAProxy is likely an issue with the reload command not being correct, thus leading to race conditions. We were experiencing similar issues but got rid of them completely as soon as we used the right reload command. See also my PR #122.

IMHO, the right solution here is to analyze and fix the HAProxy problem and not introduce more complexity into Bamboo.

**Comment by gregory90** [comment]
@timoreimann I've checked my haproxy reload command and it is not the one used in your PR. You're right, timeouts would be last resort solution.
Closing for now. I'll reopen if I hit this problem again with new reload command.
