### ISSUE TITLE
Delete REST API not working

### ISSUE THREAD

**Issue by rayjohnson** [QubitProducts/bamboo#157]
The delete API doesn't appear to work.  When doing something like this:
curl -i -X DELETE http://marathon1.np.wc1.yellowpages.com:8081/api/services//test-bamboo-prod

I am getting an error like:
405 Http method DELETE is not supported by this URL

I'm calling other APIs and they all seem to work.  Just the delete is not.

Any ideas?

Ray

**Comment by activars** [comment]
could you try this (without double // before the marathon ID in the URL)?

curl -i -X DELETE http://marathon1.np.wc1.yellowpages.com:8081/api/services/test-bamboo-prod

**Comment by activars** [comment]
em, it should work. 
It might have been a regression bug after refactoring, I flag it as bug for now.

**Comment by rayjohnson** [comment]
I did try that.  Sorry I did not mention that.  Also, I think the version
of Bamboo we have installed is 0.2.11.7

Ray

**Comment by activars** [comment]
Do you mean version 0.2.11 or 0.2.7? 

This is a release note for 0.2.11 that improves the API URL encoding issue.
https://github.com/QubitProducts/bamboo/releases/tag/v0.2.11

**Comment by activars** [comment]
close for now, I can't seem to reproduce the issue yet.
