### ISSUE TITLE
support for multiple ACLs

### ISSUE THREAD

**Issue by bhenderson** [QubitProducts/bamboo#167]
I'm trying to create an acl like:

    ssl_fc AND hdr(host) -i app.example.com

But I can't figure it out. Reading through the acl docs, it looks like haproxy expects one to create two acl lines with the same acl name. Saying that, I just realized I could modify my template to loop through $service.Acl, splitting on some delimiter like ;

Is that the recommended approach?

thanks,

**Comment by activars** [comment]
Yes, having a custom template would be better approach.
When we release new version that may contain deprecations, we often state it in the release note or add warnings into the bamboo server logs.
