### ISSUE TITLE
Dockerfile-deb, Can't load package

### ISSUE THREAD

**Issue by st15jap78** [QubitProducts/bamboo#168]
Hello all, 

I'm new to bamboo and am trying to create a deb file for my Ubuntu cluster. I followed the guide to create a deb file using docker. I used the latest Dockerfile-deb and everything seems to go fine. Then i got the following problem 
"can't load package: package github.com/QubitProducts/bamboo: no buildable Go source files in /opt/go/src/github.com/QubitProducts/bamboo
The command '/bin/sh -c go get github.com/tools/godep &&     go get -t github.com/smartystreets/goconvey &&     go build' returned a non-zero code: 1"

Is there something i am missing? Thanks for you help in advance. 

i fixed it. I am stupid.

**Comment by gom276** [comment]
Would you explain how you resolved this... I am running into the same issue.

Thanks

**Comment by st15jap78** [comment]
If my memory serves me correctly in the root directory of the server you compiled it should be a bamboo file. Either that or the root directory of the container.
