### ISSUE TITLE
bamboo configuration doesn't reload when marathon app scale,restart,migration etc.

### ISSUE THREAD

**Issue by junneyang** [QubitProducts/bamboo#170]

**Comment by activars** [comment]
which version of marathon you are running?

**Comment by junneyang** [comment]
Version 0.11.0

**Comment by junneyang** [comment]
waiting for your help, ^--^.

**Comment by rasputnik** [comment]
@junneyang get yourself onto 0.11.1 asap - there are some nasty bugs in 0.11.0
    https://github.com/mesosphere/marathon/releases
(maybe not specific to this issue but can't hurt).

**Comment by xianlubird** [comment]
I happen to have the same problem, Did you fix it ?@junneyang

**Comment by xianlubird** [comment]
My Marathon version is v0.11.1 and mesos is 0.23.0 and zookeeper is 3.4.6, waiting for help!

**Comment by junneyang** [comment]
not yet, waiting for help, ^--^

**Comment by activars** [comment]
The usual problem causing this is Bamboo requires Marathon enabling http callback. If this callback option is not set, those task events are not visible to Bamboo.

**Comment by junneyang** [comment]
thanks very much!
