### ISSUE TITLE
Time to create a new release

### ISSUE THREAD

**Issue by gomes** [QubitProducts/bamboo#173]
Hi, the last one (0.2.14) was released on 29 Jul. 21 commits is a lot to be tested in a new version.

**Comment by rasputnik** [comment]
+1 - can someone review https://github.com/QubitProducts/bamboo/pull/179 if the Release Bus is leaving town? Sneaky little bug seems to have been in there since at least 0.2.12.

**Comment by bluepeppers** [comment]
100% agree on this; I've got some largish changes and refactors in the pipeline which will be landing shortly, so I'm going to take master as-is and call it a release. Can't see any regressions on our dev cluster, and what few tests we have pass, so seems solid. I'll tag and release 0.2.15 by the end of the day.

**Comment by rasputnik** [comment]
:+1:

**Comment by bluepeppers** [comment]
https://github.com/QubitProducts/bamboo/releases/tag/v0.2.15 Enjoy
