### ISSUE TITLE
Dockerfile Build Error http.Client Timeout

### ISSUE THREAD

**Issue by scottbrumley** [QubitProducts/bamboo#182]
On building with the Dockerfile I'm getting an error message:

# github.com/QubitProducts/bamboo
./bamboo.go:185: client.Timeout undefined (type *http.Client has no field or method Timeout)

Scott

**Comment by bluepeppers** [comment]
Is this with master? The recent event streaming feature sets client.Timeout, so we may need to up the minimum Go version.

**Comment by scottbrumley** [comment]
Yes

**Comment by scottbrumley** [comment]
Just a git clone https://github.com/QubitProducts/bamboo.git

**Comment by lowstz** [comment]
Hit this issue too.

**Comment by adityareddy** [comment]
me too

**Comment by drdocker** [comment]
+1 ran into this issue as well when following the `readme` instructions for performing a Docker build. Whats the fix for this ?

**Comment by rasputnik** [comment]
Timeout was added to http.Client in Go 1.3, wasn't it?

**Comment by scottbrumley** [comment]
Looks like an issue with go lang version 1.2 in ubuntu:14.04.  So change ubuntu:14.04 in the dockerfile FROM to ubuntu:15.10 and call it a day.

**Comment by Boran** [comment]
I changed "FROM to ubuntu:15.10 " and now get pas the above error, but now have
```
Step 8 : RUN gem install fpm
 ---> Running in 0ac84ad6abf2
/bin/sh: 1: gem: not found
The command '/bin/sh -c gem install fpm' returned a non-zero code: 127
```
The fix for that was to add "RUN apt-get install -yqq gem ruby"

**Comment by scottbrumley** [comment]
Also if you want to stay with ubuntu TLS which is not a bad idea in production.  You can also just upgrade go from 1.2 to at least 1.3.  Boran that might help if you don't find an easy resolution to ruby.
