### ISSUE TITLE
Bamboo stops updating when zk connection goes away.

### ISSUE THREAD

**Issue by jdubs** [QubitProducts/bamboo#186]
Hi,
We've noticed that bamboo stops receiving updates when the connection to zookeeper temporarily goes away. Ideally, if the connection to zk goes away, bamboo should keep retrying the connection.

The relevant zk config.
  "Bamboo": {
    "Endpoint": "http://192.168.150.105:8000",
    "Zookeeper": {
      "Host": "10.0.0.11:2181,10.0.0.12:2181,10.0.0.65:2181",
      "Path": "/bamboo/state",
      "ReportingDelay": 5
    }
  },

2015-11-21 01:21:42,572 DEBG 'bamboo' stdout output:
2015/11/21 01:21:42 read tcp 10.0.0.65:2181: i/o timeout
zk: connection closedpanic: zk: connection closed

goroutine 10 [running]:
runtime.panic(0x6c4880, 0xc2100363d0)
	/usr/lib/go/src/pkg/runtime/panic.c:266 +0xb6
github.com/QubitProducts/bamboo/qzk.pollZooKeeper(0xc210069340, 0xc210036910, 0xd, 0xc21005e780, 0xc21005e720)
	/opt/go/src/github.com/QubitProducts/bamboo/qzk/qzk.go:21 +0x17b
created by github.com/QubitProducts/bamboo/qzk.ListenToConn
	/opt/go/src/github.com/QubitProducts/bamboo/qzk/qzk.go:182 +0x3ff

**Comment by Raffo** [comment]
@jdubs Can you please comment why you closed this issue?
