### ISSUE TITLE
Docker images not building deb packages

### ISSUE THREAD

**Issue by rhoml** [QubitProducts/bamboo#209]
when building the image I keep getting this errors

```
15-Jun-2016 16:01:56	can't load package: package github.com/QubitProducts/bamboo: 
15-Jun-2016 16:01:56	bamboo.go:1:1: expected 'package', found 'IDENT' main
15-Jun-2016 16:01:56	The command '/bin/sh -c go get github.com/tools/godep &&     go get -t github.com/smartystreets/goconvey &&     go build' returned a non-zero code: 1
```
Note: gem requires ruby installed on the docker containers otherwise it won't be  able to install fpm since golang image doesn't have ruby.

**Comment by activars** [comment]
Let me try to reproduce this, will get back to you later today.

**Comment by rhoml** [comment]
Thanks I am still deciding of to use it or not

**Comment by activars** [comment]
cc @rhoml 
The issue should be fixed now.
