### ISSUE TITLE
The latest version of mesos and marathon are supported ？

### ISSUE THREAD

**Issue by stevenlee87** [QubitProducts/bamboo#220]
hello!
mesos version:1.0.1
marathon version 1.1.3
Above and support?

**Comment by activars** [comment]
Mesos isn't the main dependency. The stack dependency is mainly on Marathon and zookeeper. If the new version didn't have any major changes on the callback API, everything should be fine. 
I think it's time to build some integration container to test bit more per version. 

There's a known  issue with marathon streaming as mentioned in #219 after upgrade.

**Comment by activars** [comment]
Created test feature here: #221
PR welcomed.
