### ISSUE TITLE
8125 port write: connection refused

### ISSUE THREAD

**Issue by stevenlee87** [QubitProducts/bamboo#223]
bamboo version:0.2.21
mesos version:1.0.1
marathon version:1.3.2

start command: cd /opt/bamboo;/opt/bamboo/bamboo -config /opt/bamboo/config/production.json -log /data/bamboo/log/bamboo-server.log

/opt/bamboo/config/haproxy_template.cfg use default configuration.

/opt/bamboo/config/production.json:
{
  "Marathon": {
    "Endpoint": "http://10.19.16.182:8080"
  },

  "Bamboo": {
    "Endpoint": "http://10.19.20.171:8000",
    "Zookeeper": {
      "Host": "10.19.16.182:2181,10.19.20.124:2181,10.19.20.171:2181",
      "Path": "/marathon-haproxy/state",
      "ReportingDelay": 5
    }
  },

  "HAProxy": {
    "TemplatePath": "config/haproxy_template.cfg",
    "OutputPath": "/etc/haproxy/haproxy.cfg",
    "ReloadCommand": "haproxy -f /etc/haproxy/haproxy.cfg -p /var/run/haproxy.pid -D -sf $(cat /var/run/haproxy.pid)",
    "ReloadValidationCommand": "haproxy -c -f {{.}}"
  },

  "StatsD": {
    "Enabled": true,
    "Host": "localhost:8125",
    "Prefix": "bamboo-server.development."
  }
}

after start bamboo,report this error:
2016/10/26 10:33:19 g2s: publish: write udp 127.0.0.1:26175->127.0.0.1:8125: write: connection refused
2016/10/26 10:33:19 Failed to update HAProxy configuration: exit status 1
2016/10/26 10:33:19 Generating validation command
2016/10/26 10:33:19 Validating config
2016/10/26 10:33:19 Exec cmd: haproxy -c -f /tmp/bamboo739747214 
2016/10/26 10:33:19 exit status 1
2016/10/26 10:33:19 Output:
[ALERT] 299/103319 (11093) : parsing [/tmp/bamboo739747214:28] : error opening file </etc/haproxy/errors/400.http> for custom error message <400>.
[ALERT] 299/103319 (11093) : parsing [/tmp/bamboo739747214:29] : error opening file </etc/haproxy/errors/403.http> for custom error message <403>.
[ALERT] 299/103319 (11093) : parsing [/tmp/bamboo739747214:30] : error opening file </etc/haproxy/errors/408.http> for custom error message <408>.
[ALERT] 299/103319 (11093) : parsing [/tmp/bamboo739747214:31] : error opening file </etc/haproxy/errors/500.http> for custom error message <500>.
[ALERT] 299/103319 (11093) : parsing [/tmp/bamboo739747214:32] : error opening file </etc/haproxy/errors/502.http> for custom error message <502>.
[ALERT] 299/103319 (11093) : parsing [/tmp/bamboo739747214:33] : error opening file </etc/haproxy/errors/503.http> for custom error message <503>.
[ALERT] 299/103319 (11093) : parsing [/tmp/bamboo739747214:34] : error opening file </etc/haproxy/errors/504.http> for custom error message <504>.
[ALERT] 299/103319 (11093) : Error(s) found in configuration file : /tmp/bamboo739747214
[ALERT] 299/103319 (11093) : Fatal errors found in configuration.

2016/10/26 10:33:19 Failed to update HAProxy configuration: exit status 1

**Comment by rasputnik** [comment]
It looks like you're not running statsd and you don't have custom error pages.

This doesn't look like a bug.

**Comment by stevenlee87** [comment]
statsd need to be installed and start.
