### ISSUE TITLE
Support systemd in deb package

### ISSUE THREAD

**Issue by turb** [QubitProducts/bamboo#232]
Hello,

For now, the apt build uses a symbolic link to upstart in order to manage itself as a service.

I am not very familiar with upstart, as Debian is now based on systemd. Should it be meaningful to provide a systemd definition in the deb package?

If you are ok with this, I can provide a PR, the ```fpm```option being ```--deb-systemd FILEPATH```.

(btw, it seems that ```go get``` only returns Bamboo 0.2.20, not the latest 0.2.21)

**Comment by activars** [comment]
This sounds good. Supporting systemd is the way to go. 

Happy to accept PR and fix the version issues.
