### ISSUE TITLE
Event subscription broken when using Marathon version >=1.5.0

### ISSUE THREAD

**Issue by clems4ever** [QubitProducts/bamboo#241]
Hello, 
I don't know if anyone is aware of this but I would like to let you know that I figured Bamboo (all recent releases I've checked (>=2.14) and even master branch) doesn't work with versions of Marathon superior to 1.5.0 since the endpoint /v2/eventSubscriptions in Marathon API has been deprecated and removed from Marathon as stated in this changelog: https://github.com/mesosphere/marathon/blob/v1.5.0/changelog.md.
Those events must now be read from the stream of events coming from /v2/events.

**Comment by activars** [comment]
In the current implementation, the setup can only be one or another. By setting "UseEventStream", subscription won't be registered.

```
"UseEventStream": true
```

Thanks for the heads up, I will add to the documentation.

**Comment by j1n6** [comment]
I've updated the documentation, closing the issue now. If you have any suggested documentation improvements, feel free to make a PR.

**Comment by clems4ever** [comment]
Hello @activars , thank you very much for the info and the update!
