### ISSUE TITLE
Allow multiple template file rendering 

### ISSUE THREAD

**Issue by tangicolin** [QubitProducts/bamboo#60]
In my use case i use bamboo for update HAproxy and for Redis failover.
Today i need to have one instance of Bamboo for HAproxy and one instance of Bamboo for redis failover. 
It will be nice if i can use only once instance of Bamboo to udpate HAproxy and Redis failover.

**Comment by activars** [comment]
#69 This should have resolved your concern. I'm going to close the issue for the moment.
