### ISSUE TITLE
Healthcheck on different port?

### ISSUE THREAD

**Issue by mbabineau** [QubitProducts/bamboo#62]
With `portIndex`, Marathon health checks can be configured to run against any port associated with the task:
```json
{
  "path": "/api/health",
  "portIndex": 0,
  "protocol": "HTTP",
  "gracePeriodSeconds": 30,
  "intervalSeconds": 30,
  "timeoutSeconds": 30,
  "maxConsecutiveFailures": 3
}
```

The health check port isn't currently available within Bamboo - it's simply assumed that it's equal to `$task.Port`. Consequently, configuring a Marathon app with a health check on a different port results in the app always failing HAProxy's checks.

Is there a way we could get something like `$task.HealthCheckPort`?

```
server {{ $app.EscapedId}}...check inter 30000 check port {{ $task.HealthCheckPort }}
```

**Comment by timoreimann** [comment]
@activars: I see you added the _waiting for response_ label. Is there anything we can provide to help move forward with this issue?

We are also interested in Bamboo support for health-checking a different port. Let us know if there's anything we can do to assist you folks.

Thanks!

**Comment by activars** [comment]
To support this, I would like to support multiple healthchecks per backend server. For example, a Marathon app may have checks for  TCP port 3000 and HTTP port 4000. Both check should be reflected to HAproxy routing logic.

This means, Bamboo needs to be refactored to support array of healthchecks:
 - support HTTP
 - support TCP
 - possible command check (as Marathon support this)

I wonder if there is an workaround. So, instead of actually checking them (reinvent the wheel), it would be great just let HAProxy validate the application status from Marathons API, thus a single check will reflect the status of the service.

**Comment by timoreimann** [comment]
@activars Sounds promising. Marathon does [publish health check changes through its event bus](https://mesosphere.github.io/marathon/docs/event-bus.html), so Bamboo could tap into that. I agree that doubling the check seems unnecessary for backends that already take care of service healthiness.

Need help implementing? I could take a stab.

**Comment by activars** [comment]
Hi, I'm open to PRs and any contributions.

On 13 Mar 2015, at 19:20, Timo Reimann <notifications@github.com> wrote:

@activars <https://github.com/activars> Sounds promising. Marathon does publish
health check changes through its event bus
<https://mesosphere.github.io/marathon/docs/event-bus.html>, so Bamboo
could tap into that. I agree that doubling the check seems unnecessary for
backends that already take care of service healthiness.

Need help implementing? I could take a stab.

—
Reply to this email directly or view it on GitHub
<https://github.com/QubitProducts/bamboo/issues/62#issuecomment-79274269>.

**Comment by timoreimann** [comment]
Did you implement this?

**Comment by activars** [comment]
No, I'm merging this issue with the healthcheck improvements. Duplicate #57 
I think this also relates to multiple service ports, api and ui improvements. I need to think about refactoring and not breaking existing APIs.

**Comment by timoreimann** [comment]
Okay, makes sense. It's just that #57 does not explicitly mention the idea of supporting multiple ports, which I think was the original intention for this issue.

(Although I'm more interested in the "just reuse health checks from Marathon" idea by know because that seems to be the right approach.)

**Comment by activars** [comment]
I agree with your suggestion. I don't want to reimplement the robust featured healthcheck that marathon provides.
