### ISSUE TITLE
Bamboo on every mesos slave and Marathon callback

### ISSUE THREAD

**Issue by gregory90** [QubitProducts/bamboo#73]
Not sure if bug, but...
When running Bamboo on every mesos slave should I have callback in Marathon for each instance of Bamboo?
I thought one callback will be enough, but updates doesn't seem to propagate to other instances.

**Comment by sttts** [comment]
That's normal right now. Not sure it is worth it to change because the network traffic has to take place somewhere. Now the marathon instance does the work. The only thing is that the logging of marathon is quite verbose about that.

**Comment by gregory90** [comment]
Thanks! Just wanted to make sure I'm doing everything the right way.
