### ISSUE TITLE
Lumberjack "Logger" struct giving build error

### ISSUE THREAD

**Issue by Joachricar** [QubitProducts/bamboo#74]
Hi there.

When building bamboo.go, I got a build error on line 152(Filename: logPath)
According to [these docs](https://godoc.org/github.com/natefinch/lumberjack) there is no "Filename".
Changing "Filename" to "Dir" fixed the error for me :)

**Comment by activars** [comment]
Hello, it's likely the dependency wasn't restored correctly, try this:

```
# Pakcage manager
go get github.com/tools/godep
go get -t github.com/smartystreets/goconvey

cd $GOPATH/github.com/QubitProducts/bamboo
godep restore

# Build your binary
go build
```

**Comment by Joachricar** [comment]
Ahh, yes. That worked too.
godep segfaults 50% of the times running it, including when i downloaded bamboo. Thanks :)

**Comment by activars** [comment]
Thanks for the update.
