### ISSUE TITLE
URI encoded marathon application ids are double encoded

### ISSUE THREAD

**Issue by lo1tuma** [QubitProducts/bamboo#80]
The README about the REST API says that marathon application ids have to be URI encoded. The given examples in the documentation are actually double encoded. I’ve tried both, single encoded and double encoded marathon app ids, the REST API only works with double encoded ids.

1. Example from documentdation: `curl -i -X DELETE http://localhost:8000/api/services/%252Fapp-1`
2. Decoded: `http://localhost:8000/api/services/%2Fapp-1`
3. Decoded again: `http://localhost:8000/api/services//app-1`

**Comment by activars** [comment]
closed by #109
