### ISSUE TITLE
multiple master configuration

### ISSUE THREAD

**Issue by elmalto** [QubitProducts/bamboo#82]
Hi,

sorry for posting this question, but I cannot get it to work properly:

I have a 3 master setup and the following config.json:
```
{
  "Marathon": {
    "Endpoint": "http://localhost:8080"
  },

  "Bamboo": {
    "Endpoint": "http://masterN:8000", # this is the local IP of this master
    "Zookeeper": {
      "Host": "master0:2181,master1:2181,master2:2181",
      "Path": "/marathon-haproxy/state",
      "ReportingDelay": 5
    }
  },

  "HAProxy": {
    "TemplatePath": "/opt/bamboo/config/haproxy_template.cfg",
    "OutputPath": "/etc/haproxy/haproxy.cfg",
    "ReloadCommand": "PIDS=`pidof haproxy`; haproxy -f /etc/haproxy/haproxy.cfg -p /var/run/haproxy.pid -sf $PIDS && while ps -p $PIDS; do sleep 0.2; done"
  },

  "StatsD": {
    "Enabled": false,
    "Host": "localhost:8125",
    "Prefix": "bamboo-server.development."
  }
}
```

explanation: as a bamboo endpoint I used each master's ip address, marathon endpoint is localhost and the zookeeper hosts are my three master ip addresses. Now my website switches between available and 503 in a millisecond manner. How do I make this setup work?

**Comment by elmalto** [comment]
I don't know why I set them up on the master. Sorry about that :)

**Comment by activars** [comment]
did you managed to get it working?

**Comment by elmalto** [comment]
yes I did. used the slaves instead of the masters for bamboo and added all master ips as marathon hosts

**Comment by activars** [comment]
Thanks, that's great to know. Thanks for he update.

On 28 Feb 2015, at 00:52, elmalto <notifications@github.com> wrote:

yes I did. used the slaves instead of the masters for bamboo and added all
master ips as marathon hosts

—
Reply to this email directly or view it on GitHub
<https://github.com/QubitProducts/bamboo/issues/82#issuecomment-76499873>.
