### ISSUE TITLE
Docker Container Fails to Deploy

### ISSUE THREAD

**Issue by mikealbert** [QubitProducts/bamboo#85]
Hi,

I'm attempting to deploy bamboo in a docker container as described in the documentation.  I've built the docker image, but it is unable to find the config file when I run it.  Here's what I'm seeing:

```
[root@bamboo bamboo-0.2.9]# ls -l config/bamboo_test.json
-rw-r--r--. 1 root root 642 Mar  6 20:51 config/bamboo_test.json
[root@bamboo bamboo-0.2.9]# docker run -t -i --rm -p 8000:8000 -p 80:80 \
     -e MARATHON_ENDPOINT=http://xxx.xxx.xxx.xxx:8080 \
     -e BAMBOO_ENDPOINT=http://xxx.xxx.xxx.xxx:8000 \
     -e BAMBOO_ZK_HOST=xxx.xxx.xxx.xxx:2181 \
     -e BAMBOO_ZK_PATH=/bamboo \
     -e BIND=":8000" \
     -e CONFIG_PATH="config/bamboo_test.json" \
     -e BAMBOO_DOCKER_AUTO_HOST=true \
     bamboo
sed: can't read config/bamboo_test.json: No such file or directory
```

Thanks in advance for the help.

**Comment by mbabineau** [comment]
`CONFIG_PATH` should be a path inside the container. If you want to inject an external config, just mount the volume and set your `CONFIG_PATH` to the config inside the mount.

Like so:
```bash
docker run -t -i --rm -p 8000:8000 -p 80:80 \
     -v `pwd`/config:/myconfig
     -e MARATHON_ENDPOINT=http://xxx.xxx.xxx.xxx:8080 \
     -e BAMBOO_ENDPOINT=http://xxx.xxx.xxx.xxx:8000 \
     -e BAMBOO_ZK_HOST=xxx.xxx.xxx.xxx:2181 \
     -e BAMBOO_ZK_PATH=/bamboo \
     -e BIND=":8000" \
     -e CONFIG_PATH="/myconfig/bamboo_test.json" \
     -e BAMBOO_DOCKER_AUTO_HOST=true \
     bamboo
```

**Comment by mikealbert** [comment]
Great.  That did the trick.  So if I have the custom config in place prior to building the container, would I no longer need to mount the external volume?

Thanks for the help.

**Comment by mbabineau** [comment]
Correct, so long as the file can be referenced from within the container, you're set

**Comment by mikealbert** [comment]
Perfect.

Thanks again for the help and quick response.

**Comment by activars** [comment]
@mbabineau  Thanks for helping out support questions.
