### ISSUE TITLE
HAProxy http_check configuration setting treats non-empty 404 errors as healthy indicator 

### ISSUE THREAD

**Issue by timoreimann** [QubitProducts/bamboo#90]
Using a version of Bamboo that includes commit 6791f2606252622194e22724897e2228adfe57c1, it comes with a change to the HAProxy configuration template backend section that treats a HTTP response with a non-empty body as a positive health signal. The configuration change in questions is this:

`http-check expect rstring .*`

What this means is that even if you specify an non-existing URI in the `httpchk` option leading to a 404 response, you will still end up with a health check considered valid if the response contains some string like _Not Found_. In fact, this is the exact scenario that we ran into using Bamboo.

I couldn't fully understand from the git commit message what the reason was to make the change, so I am uncertain how a proper fix would look like. The `http-check` regular expression _could_ be extended to cover 2xx and 3xx responses (as in `^[23]\d{2}.*`), but that seems no different to leaving out the entire parameter (as `httpchk`defaults to considering 2xx/3xx as valid).

Maybe @activars (the commit author) can shed some light on what the intention for the change was in the first place.

Thanks!

**Comment by activars** [comment]
HAProxy health check drops connection early. This means it doesn't wait for http body to arrive and close the connection.

We had a couple of Python HTTP service using popular frameworks that doesn't handle it well. Adding `http-check expect rstring .*` force waiting for the body to arrive...

I think this should be handled by the HTTP server, this feels like a hack (Sorry).

**Comment by timoreimann** [comment]
Thanks for the quick feedback. So if I understand you correctly, then you're fine with removing the configuration setting in question? If so, then I'll follow up with a PR.

**Comment by activars** [comment]
I'm fine with that. :)
