### ISSUE TITLE
statsd counters with marathon 0.7.5+

### ISSUE THREAD

**Issue by rasputnik** [QubitProducts/bamboo#94]
Noticed on marathon 0.7.5 that task reconciliation kicks in every 30 seconds
by default, all tasks being reported as TASK_RUNNING.

(This was a big reason for us to run Bamboo; reloading only when tasks have changed).

the statsd metrics show marathon events happening every 30 seconds - is it possible
to add a metric that fires only when a haproxy reload takes place? I suppose I could hack one
into the haproxy reload command, but it seems a bit unnecessary when all the machinery is ready
to go in bamboo itself.

**Comment by activars** [comment]
the desinged behaviour was suppose to send statsd only when the a reload event triggered. This was working when marathon was 0.6. After refactoring for marathon 0.7.*, the original behviour has changed. 

So what you want is suppose to be correct behaviour.

The simple fix is delete this line:
https://github.com/QubitProducts/bamboo/blob/58e198cf19a9fa31cd9734f62db48eab25be4c30/services/event_bus/event_handler.go#L43

Add the statsd incremental to somewhere here:
https://github.com/QubitProducts/bamboo/blob/58e198cf19a9fa31cd9734f62db48eab25be4c30/services/event_bus/event_handler.go#L94

**Comment by rasputnik** [comment]
Don't have a problem with them both being there actually - I'd like to alert on this data
just in case one of the bamboo instances loses connectivity with marathon for some reason.

How about we call the one on L37 'callback.marathon' to show an event fired,
and move 'reload.marathon' to L94?

I'll send a PR for that, let me know if you want to tweak it.
